version: '3'

services:
  db:
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data